var dir_b2c8604a5d64c8a8c2b2f4e9ced3b1cb =
[
    [ "OuterMessage.cs", "_unity_2_codes_2_model_2_generate_2_message_2_outer_message_8cs.html", [
      [ "ET.C2M_TestRequest", "class_e_t_1_1_c2_m___test_request.html", "class_e_t_1_1_c2_m___test_request" ],
      [ "ET.M2C_TestResponse", "class_e_t_1_1_m2_c___test_response.html", "class_e_t_1_1_m2_c___test_response" ],
      [ "ET.Actor_TransferRequest", "class_e_t_1_1_actor___transfer_request.html", "class_e_t_1_1_actor___transfer_request" ],
      [ "ET.Actor_TransferResponse", "class_e_t_1_1_actor___transfer_response.html", "class_e_t_1_1_actor___transfer_response" ],
      [ "ET.C2G_EnterMap", "class_e_t_1_1_c2_g___enter_map.html", "class_e_t_1_1_c2_g___enter_map" ],
      [ "ET.G2C_EnterMap", "class_e_t_1_1_g2_c___enter_map.html", "class_e_t_1_1_g2_c___enter_map" ],
      [ "ET.MoveInfo", "class_e_t_1_1_move_info.html", "class_e_t_1_1_move_info" ],
      [ "ET.UnitInfo", "class_e_t_1_1_unit_info.html", "class_e_t_1_1_unit_info" ],
      [ "ET.M2C_CreateUnits", "class_e_t_1_1_m2_c___create_units.html", "class_e_t_1_1_m2_c___create_units" ],
      [ "ET.M2C_CreateMyUnit", "class_e_t_1_1_m2_c___create_my_unit.html", "class_e_t_1_1_m2_c___create_my_unit" ],
      [ "ET.M2C_StartSceneChange", "class_e_t_1_1_m2_c___start_scene_change.html", "class_e_t_1_1_m2_c___start_scene_change" ],
      [ "ET.M2C_RemoveUnits", "class_e_t_1_1_m2_c___remove_units.html", "class_e_t_1_1_m2_c___remove_units" ],
      [ "ET.C2M_PathfindingResult", "class_e_t_1_1_c2_m___pathfinding_result.html", "class_e_t_1_1_c2_m___pathfinding_result" ],
      [ "ET.C2M_Stop", "class_e_t_1_1_c2_m___stop.html", "class_e_t_1_1_c2_m___stop" ],
      [ "ET.M2C_PathfindingResult", "class_e_t_1_1_m2_c___pathfinding_result.html", "class_e_t_1_1_m2_c___pathfinding_result" ],
      [ "ET.M2C_Stop", "class_e_t_1_1_m2_c___stop.html", "class_e_t_1_1_m2_c___stop" ],
      [ "ET.C2G_Ping", "class_e_t_1_1_c2_g___ping.html", "class_e_t_1_1_c2_g___ping" ],
      [ "ET.G2C_Ping", "class_e_t_1_1_g2_c___ping.html", "class_e_t_1_1_g2_c___ping" ],
      [ "ET.G2C_Test", "class_e_t_1_1_g2_c___test.html", null ],
      [ "ET.C2M_Reload", "class_e_t_1_1_c2_m___reload.html", "class_e_t_1_1_c2_m___reload" ],
      [ "ET.M2C_Reload", "class_e_t_1_1_m2_c___reload.html", "class_e_t_1_1_m2_c___reload" ],
      [ "ET.C2R_Register", "class_e_t_1_1_c2_r___register.html", "class_e_t_1_1_c2_r___register" ],
      [ "ET.R2C_Register", "class_e_t_1_1_r2_c___register.html", "class_e_t_1_1_r2_c___register" ],
      [ "ET.C2R_Login", "class_e_t_1_1_c2_r___login.html", "class_e_t_1_1_c2_r___login" ],
      [ "ET.R2C_Login", "class_e_t_1_1_r2_c___login.html", "class_e_t_1_1_r2_c___login" ],
      [ "ET.C2G_LoginGate", "class_e_t_1_1_c2_g___login_gate.html", "class_e_t_1_1_c2_g___login_gate" ],
      [ "ET.G2C_LoginGate", "class_e_t_1_1_g2_c___login_gate.html", "class_e_t_1_1_g2_c___login_gate" ],
      [ "ET.G2C_TestHotfixMessage", "class_e_t_1_1_g2_c___test_hotfix_message.html", "class_e_t_1_1_g2_c___test_hotfix_message" ],
      [ "ET.C2M_TestRobotCase", "class_e_t_1_1_c2_m___test_robot_case.html", "class_e_t_1_1_c2_m___test_robot_case" ],
      [ "ET.M2C_TestRobotCase", "class_e_t_1_1_m2_c___test_robot_case.html", "class_e_t_1_1_m2_c___test_robot_case" ],
      [ "ET.C2M_TransferMap", "class_e_t_1_1_c2_m___transfer_map.html", "class_e_t_1_1_c2_m___transfer_map" ],
      [ "ET.M2C_TransferMap", "class_e_t_1_1_m2_c___transfer_map.html", "class_e_t_1_1_m2_c___transfer_map" ],
      [ "ET.C2G_LeaveMap", "class_e_t_1_1_c2_g___leave_map.html", "class_e_t_1_1_c2_g___leave_map" ],
      [ "ET.G2C_LeaveMap", "class_e_t_1_1_g2_c___leave_map.html", "class_e_t_1_1_g2_c___leave_map" ]
    ] ],
    [ "OuterOpcode.cs", "_unity_2_codes_2_model_2_generate_2_message_2_outer_opcode_8cs.html", null ]
];